-- =====================================================================================
-- V1: the durable incident lifecycle.
--
-- Scope note: this migration covers the tables the incident lifecycle needs. The ADK
-- session, event, memory and artifact tables arrive in V2 alongside PostgresSessionService,
-- and the agent telemetry tables (tool_calls, model_calls, specialist_outputs) in V3 with
-- the code that writes them. Creating tables ahead of the code that uses them produces
-- schema nobody validates, so each table lands together with its reader and writer.
--
-- Conventions:
--   * UUID primary keys, generated by the application so ids exist before insert.
--   * TIMESTAMPTZ everywhere. An incident timeline that loses its offset is worthless.
--   * JSONB only where the payload is genuinely open-ended. Anything queried is a column.
--   * Every index below states the query that justifies it.
-- =====================================================================================

-- -------------------------------------------------------------------------------------
-- Actors
-- -------------------------------------------------------------------------------------
CREATE TABLE actors (
    id           TEXT PRIMARY KEY,
    display_name TEXT        NOT NULL,
    role         TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT actors_role_valid CHECK (role IN ('VIEWER', 'INVESTIGATOR', 'APPROVER'))
);

COMMENT ON TABLE actors IS
    'Principals that may act on incidents. Approval decisions reference this table so that '
    '"who approved this" is answerable without inference.';

INSERT INTO actors (id, display_name, role)
VALUES ('system', 'Incident Commander', 'VIEWER');

-- -------------------------------------------------------------------------------------
-- Incidents: the aggregate root
-- -------------------------------------------------------------------------------------
CREATE TABLE incidents (
    id           UUID PRIMARY KEY,
    title        TEXT        NOT NULL,
    service_name TEXT        NOT NULL,
    environment  TEXT        NOT NULL,
    severity     TEXT        NOT NULL,
    status       TEXT        NOT NULL,
    version      BIGINT      NOT NULL,
    received_at  TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    summary      TEXT,
    closing_note TEXT,

    CONSTRAINT incidents_title_present  CHECK (length(btrim(title)) > 0),
    CONSTRAINT incidents_version_valid  CHECK (version >= 0),
    CONSTRAINT incidents_time_ordered   CHECK (updated_at >= received_at),
    CONSTRAINT incidents_severity_valid CHECK (severity IN ('SEV1', 'SEV2', 'SEV3', 'SEV4')),
    CONSTRAINT incidents_status_valid   CHECK (status IN (
        'RECEIVED', 'INVESTIGATING', 'FORMING_HYPOTHESIS', 'PLANNING_REMEDIATION',
        'AWAITING_APPROVAL', 'REMEDIATING', 'VERIFYING',
        'RESOLVED', 'REJECTED', 'FAILED', 'CANCELLED'))
);

COMMENT ON COLUMN incidents.version IS
    'Optimistic-locking version. Also an input to the approval fingerprint, so any material '
    'change to an incident invalidates approvals outstanding against it (ADR-0007).';

-- Query: the operator console lists open incidents, newest first.
CREATE INDEX incidents_open_by_recency
    ON incidents (updated_at DESC)
    WHERE status NOT IN ('RESOLVED', 'REJECTED', 'FAILED', 'CANCELLED');

-- Query: on startup, find incidents stranded mid-approval so they can be resumed.
CREATE INDEX incidents_awaiting_approval
    ON incidents (received_at)
    WHERE status = 'AWAITING_APPROVAL';

-- -------------------------------------------------------------------------------------
-- Status transitions
-- -------------------------------------------------------------------------------------
CREATE TABLE incident_status_transitions (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    incident_id UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    from_status TEXT,
    to_status   TEXT        NOT NULL,
    to_version  BIGINT      NOT NULL,
    actor_id    TEXT        NOT NULL REFERENCES actors (id),
    reason      TEXT,
    occurred_at TIMESTAMPTZ NOT NULL
);

-- Query: render one incident's timeline in order. The id tiebreaks same-instant rows.
CREATE INDEX incident_transitions_by_incident
    ON incident_status_transitions (incident_id, occurred_at, id);

-- -------------------------------------------------------------------------------------
-- Evidence and gaps
-- -------------------------------------------------------------------------------------
CREATE TABLE evidence (
    id           UUID PRIMARY KEY,
    incident_id  UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    source       TEXT        NOT NULL,
    collected_by TEXT        NOT NULL,
    summary      TEXT        NOT NULL,
    content      TEXT        NOT NULL,
    confidence   DOUBLE PRECISION NOT NULL,
    untrusted    BOOLEAN     NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    observed_at  TIMESTAMPTZ,

    CONSTRAINT evidence_confidence_bounded CHECK (confidence >= 0.0 AND confidence <= 1.0),
    CONSTRAINT evidence_content_bounded    CHECK (length(content) <= 16000),
    CONSTRAINT evidence_summary_present    CHECK (length(btrim(summary)) > 0)
);

COMMENT ON COLUMN evidence.untrusted IS
    'True when the source can carry attacker-influenced free text (logs, CloudTrail). Such '
    'content is sanitised and explicitly delimited before it is ever placed in a prompt.';

COMMENT ON CONSTRAINT evidence_content_bounded ON evidence IS
    'Mirrors Evidence.MAX_CONTENT_LENGTH. Unbounded tool output is both a cost problem and a '
    'prompt-injection surface, so the bound is enforced in two places on purpose.';

-- Query: list all evidence for an incident, newest first, for the console and the report.
CREATE INDEX evidence_by_incident ON evidence (incident_id, collected_at DESC);

-- Query: "what did the logs investigator find for this incident?"
CREATE INDEX evidence_by_incident_source ON evidence (incident_id, source);

CREATE TABLE evidence_gaps (
    id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    incident_id  UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    source       TEXT        NOT NULL,
    attempted_by TEXT        NOT NULL,
    reason       TEXT        NOT NULL,
    detail       TEXT        NOT NULL,
    recorded_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT evidence_gaps_reason_valid CHECK (reason IN (
        'TIMEOUT', 'UPSTREAM_ERROR', 'NO_DATA', 'ACCESS_DENIED', 'BUDGET_EXHAUSTED'))
);

COMMENT ON TABLE evidence_gaps IS
    'Evidence that should exist but could not be obtained. Recorded separately from evidence '
    'so the report can distinguish "the logs showed nothing" from "the logs could not be read".';

CREATE INDEX evidence_gaps_by_incident ON evidence_gaps (incident_id, recorded_at);

-- -------------------------------------------------------------------------------------
-- Hypotheses
-- -------------------------------------------------------------------------------------
CREATE TABLE hypotheses (
    id                     UUID             NOT NULL,
    revision               INTEGER          NOT NULL,
    incident_id            UUID             NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    statement              TEXT             NOT NULL,
    reasoning              TEXT             NOT NULL,
    confidence             DOUBLE PRECISION NOT NULL,
    supporting_evidence    UUID[]           NOT NULL,
    contradicting_evidence UUID[]           NOT NULL,
    created_at             TIMESTAMPTZ      NOT NULL,

    -- Identity is (id, revision): a refinement is a new row, never an update. The reasoning
    -- trail is part of the postmortem, and the discarded explanation is often the interesting
    -- part of an investigation.
    PRIMARY KEY (id, revision),

    CONSTRAINT hypotheses_confidence_bounded CHECK (confidence >= 0.0 AND confidence <= 1.0),
    CONSTRAINT hypotheses_revision_valid     CHECK (revision >= 0),
    CONSTRAINT hypotheses_statement_present  CHECK (length(btrim(statement)) > 0),
    -- Mirrors the domain invariant: an unsupported hypothesis is not representable.
    CONSTRAINT hypotheses_must_cite_evidence CHECK (cardinality(supporting_evidence) > 0)
);

-- Query: fetch the latest revision of each hypothesis for an incident.
CREATE INDEX hypotheses_by_incident ON hypotheses (incident_id, revision DESC);

-- -------------------------------------------------------------------------------------
-- Remediation proposals and policy decisions
-- -------------------------------------------------------------------------------------
CREATE TABLE remediation_proposals (
    id                  UUID PRIMARY KEY,
    incident_id         UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    hypothesis_id       UUID        NOT NULL,
    hypothesis_revision INTEGER     NOT NULL,
    action_type         TEXT        NOT NULL,
    target_arn          TEXT        NOT NULL,
    target_account_id   TEXT        NOT NULL,
    target_region       TEXT        NOT NULL,
    target_environment  TEXT        NOT NULL,
    target_resource_type TEXT       NOT NULL,
    -- Open-ended by nature: argument names differ per action type. Justified JSONB.
    arguments           JSONB       NOT NULL DEFAULT '{}'::jsonb,
    human_description   TEXT        NOT NULL,
    expected_impact     TEXT        NOT NULL,
    proposed_at         TIMESTAMPTZ NOT NULL,

    FOREIGN KEY (hypothesis_id, hypothesis_revision) REFERENCES hypotheses (id, revision),
    CONSTRAINT remediation_action_type_valid CHECK (action_type IN (
        'DEACTIVATE_DEMO_FAULT', 'RESTORE_SAFE_CONFIGURATION', 'RUN_HEALTH_CHECK',
        'RESTART_ECS_TASK', 'SCALE_ECS_SERVICE', 'ROLLBACK_DEPLOYMENT'))
);

COMMENT ON COLUMN remediation_proposals.hypothesis_id IS
    'Every proposal is traceable to the exact hypothesis revision that motivated it. Without '
    'this a report could not honestly explain why an action was taken.';

CREATE INDEX remediation_proposals_by_incident ON remediation_proposals (incident_id, proposed_at);

CREATE TABLE policy_decisions (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    incident_id   UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    proposal_id   UUID        NOT NULL REFERENCES remediation_proposals (id) ON DELETE CASCADE,
    -- 'GATE' is the pre-approval evaluation; 'EXECUTION' is the re-check inside the tool body.
    -- Both are recorded, because the whole safety argument rests on the second one happening.
    evaluation_phase TEXT     NOT NULL,
    allowed       BOOLEAN     NOT NULL,
    approval_required BOOLEAN NOT NULL,
    assessed_risk TEXT,
    violations    JSONB       NOT NULL DEFAULT '[]'::jsonb,
    explanation   TEXT        NOT NULL,
    decided_at    TIMESTAMPTZ NOT NULL,

    CONSTRAINT policy_phase_valid CHECK (evaluation_phase IN ('GATE', 'EXECUTION')),
    CONSTRAINT policy_risk_valid  CHECK (assessed_risk IS NULL OR assessed_risk IN (
        'NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    -- A denial must say why; an allow must carry a risk classification.
    CONSTRAINT policy_denial_has_violations CHECK (
        (allowed AND assessed_risk IS NOT NULL) OR
        (NOT allowed AND jsonb_array_length(violations) > 0))
);

CREATE INDEX policy_decisions_by_proposal ON policy_decisions (proposal_id, decided_at);

-- -------------------------------------------------------------------------------------
-- Approvals
-- -------------------------------------------------------------------------------------
CREATE TABLE approval_requests (
    id                   UUID PRIMARY KEY,
    incident_id          UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    proposal_id          UUID        NOT NULL REFERENCES remediation_proposals (id) ON DELETE CASCADE,
    incident_version     BIGINT      NOT NULL,
    fingerprint          CHAR(64)    NOT NULL,
    risk                 TEXT        NOT NULL,
    rationale            TEXT        NOT NULL,
    expected_impact      TEXT        NOT NULL,
    supporting_evidence  UUID[]      NOT NULL,
    status               TEXT        NOT NULL,
    requested_at         TIMESTAMPTZ NOT NULL,
    expires_at           TIMESTAMPTZ NOT NULL,
    adk_function_call_id TEXT,

    CONSTRAINT approval_status_valid CHECK (status IN (
        'PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'SUPERSEDED', 'CANCELLED')),
    CONSTRAINT approval_risk_valid CHECK (risk IN ('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT approval_expiry_after_request CHECK (expires_at > requested_at),
    CONSTRAINT approval_fingerprint_is_hex CHECK (fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT approval_cites_evidence CHECK (cardinality(supporting_evidence) > 0)
);

COMMENT ON COLUMN approval_requests.fingerprint IS
    'SHA-256 over the action, target, arguments, incident id and incident version. Recomputed '
    'and compared before execution; a mismatch means the approval is stale (ADR-0007).';

COMMENT ON COLUMN approval_requests.adk_function_call_id IS
    'The id of the ADK adk_request_confirmation function call this approval will resume. '
    'Persisted so a restarted process can replay the FunctionResponse into the right call.';

-- At most one approval may be outstanding per incident. This is a structural defence against
-- two concurrent proposals racing to be approved and both executing.
CREATE UNIQUE INDEX approval_one_pending_per_incident
    ON approval_requests (incident_id)
    WHERE status = 'PENDING';

-- Query: the approvals queue, and the expiry sweep.
CREATE INDEX approval_pending_by_expiry
    ON approval_requests (expires_at)
    WHERE status = 'PENDING';

CREATE TABLE approval_decisions (
    id                     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    approval_id            UUID        NOT NULL REFERENCES approval_requests (id) ON DELETE CASCADE,
    decided_by             TEXT        NOT NULL REFERENCES actors (id),
    outcome                TEXT        NOT NULL,
    fingerprint_at_decision CHAR(64)   NOT NULL,
    comment                TEXT,
    decided_at             TIMESTAMPTZ NOT NULL,

    CONSTRAINT approval_outcome_valid CHECK (outcome IN ('APPROVED', 'REJECTED')),
    -- One decision per approval. A second attempt is a replay and must fail loudly.
    CONSTRAINT approval_decision_unique UNIQUE (approval_id)
);

COMMENT ON COLUMN approval_decisions.fingerprint_at_decision IS
    'The fingerprint as it stood when the human decided. Stored separately from the request so '
    'the audit trail shows exactly what was authorised, even if the request were later altered.';

-- -------------------------------------------------------------------------------------
-- Executed actions and idempotency
-- -------------------------------------------------------------------------------------
CREATE TABLE idempotency_keys (
    fingerprint  CHAR(64) PRIMARY KEY,
    incident_id  UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    first_seen_at TIMESTAMPTZ NOT NULL,
    outcome      TEXT        NOT NULL,
    result       JSONB       NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT idempotency_fingerprint_is_hex CHECK (fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT idempotency_outcome_valid CHECK (outcome IN ('IN_PROGRESS', 'SUCCEEDED', 'FAILED'))
);

COMMENT ON TABLE idempotency_keys IS
    'Keyed on the action fingerprint. Inserting the key is the claim to execute: the primary key '
    'makes a duplicate attempt fail at the database, so exactly-once execution does not depend on '
    'application-level locking or on callers behaving well.';

CREATE TABLE executed_actions (
    id            UUID PRIMARY KEY,
    incident_id   UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    approval_id   UUID        NOT NULL REFERENCES approval_requests (id),
    fingerprint   CHAR(64)    NOT NULL REFERENCES idempotency_keys (fingerprint),
    action_type   TEXT        NOT NULL,
    target_arn    TEXT        NOT NULL,
    dry_run       BOOLEAN     NOT NULL,
    outcome       TEXT        NOT NULL,
    detail        TEXT,
    started_at    TIMESTAMPTZ NOT NULL,
    finished_at   TIMESTAMPTZ,

    CONSTRAINT executed_outcome_valid CHECK (outcome IN ('SUCCEEDED', 'FAILED', 'SKIPPED_DUPLICATE'))
);

COMMENT ON COLUMN executed_actions.dry_run IS
    'Whether this was simulated. Recorded per execution rather than inferred from configuration, '
    'so a report can never imply a real change was made when it was not.';

CREATE INDEX executed_actions_by_incident ON executed_actions (incident_id, started_at);

-- -------------------------------------------------------------------------------------
-- Verification and reports
-- -------------------------------------------------------------------------------------
CREATE TABLE verification_results (
    id                 UUID PRIMARY KEY,
    incident_id        UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    executed_action_id UUID        NOT NULL REFERENCES executed_actions (id) ON DELETE CASCADE,
    recovered          BOOLEAN     NOT NULL,
    summary            TEXT        NOT NULL,
    evidence_ids       UUID[]      NOT NULL,
    verified_at        TIMESTAMPTZ NOT NULL,

    CONSTRAINT verification_cites_evidence CHECK (cardinality(evidence_ids) > 0)
);

CREATE TABLE reports (
    id            UUID PRIMARY KEY,
    incident_id   UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    markdown      TEXT        NOT NULL,
    evidence_ids  UUID[]      NOT NULL,
    generated_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX reports_by_incident ON reports (incident_id, generated_at DESC);

-- -------------------------------------------------------------------------------------
-- Audit log: append-only, enforced by the database
-- -------------------------------------------------------------------------------------
CREATE TABLE audit_events (
    sequence       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    incident_id    UUID        NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
    event_type     TEXT        NOT NULL,
    actor_id       TEXT        NOT NULL REFERENCES actors (id),
    summary        TEXT        NOT NULL,
    details        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    security_relevant BOOLEAN  NOT NULL,
    correlation_id TEXT,
    occurred_at    TIMESTAMPTZ NOT NULL,

    CONSTRAINT audit_summary_present CHECK (length(btrim(summary)) > 0)
);

COMMENT ON COLUMN audit_events.sequence IS
    'Monotonic insert order. Two events can share a millisecond, and a reader still needs to '
    'know which came first, so ordering never relies on occurred_at alone.';

-- Query: the incident audit trail, in order.
CREATE INDEX audit_events_by_incident ON audit_events (incident_id, sequence);

-- Query: the security review subset, across all incidents.
CREATE INDEX audit_events_security
    ON audit_events (occurred_at DESC)
    WHERE security_relevant;

-- An audit log the application can rewrite is not an audit log, and the one moment it would
-- matter is exactly the moment something has gone wrong. A trigger is used rather than a GRANT
-- so the guarantee holds regardless of which role connects, and so it is directly testable.
--
-- The trigger has one deliberate escape hatch. Without it, audit_events could never be removed,
-- and because incidents cascade to their audit entries, no incident could ever be deleted either
-- -- which would make data retention impossible and leave the demo unable to clean up after
-- itself. Rather than weaken the rule, maintenance must announce itself:
--
--     SET LOCAL app.audit_maintenance = 'on';
--
-- The setting is transaction-scoped (SET LOCAL), so it cannot leak into subsequent work on a
-- pooled connection. This is not a security boundary against an attacker who already holds
-- arbitrary SQL access -- nothing at this layer could be. It is a boundary against the
-- application's own ordinary code paths: no repository, service or stray "cleanup" query can
-- rewrite history without stating that intent in a form that shows up in review and in an audit
-- of the code.
CREATE OR REPLACE FUNCTION reject_audit_mutation() RETURNS trigger AS $$
BEGIN
    IF current_setting('app.audit_maintenance', true) = 'on' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    RAISE EXCEPTION 'audit_events is append-only; % is not permitted', TG_OP
        USING ERRCODE = 'restrict_violation',
              HINT = 'Retention and cleanup must set app.audit_maintenance for the transaction.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_events_append_only
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();

COMMENT ON TRIGGER audit_events_append_only ON audit_events IS
    'Enforces append-only at the database. Verified by AuditLogIntegrationTest, which asserts '
    'that UPDATE and DELETE both raise, and that the maintenance escape hatch is explicit.';
